setup: &setup
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *setup
  database: project_development

test:
  <<: *setup
  database: project_test